/**
 * Apple's territory list — A SNAPSHOT, not a live read.
 *
 * ─── WHAT THIS IS ──────────────────────────────────────────────────────────
 *
 *   MEASURED   2026-08-27, `GET /v1/territories?limit=200`, 175 territories,
 *              each with the currency Apple bills it in.
 *   REFRESH    ASC_KEY_ID=… ASC_ISSUER_ID=… \
 *                ASC_PRIVATE_KEY="$(cat AuthKey_XXXX.p8)" \
 *                node scripts/probe-export-price-sources.mjs
 *              Step 2.6b prints the whole table as TypeScript between copy
 *              markers; step 2.7 DIFFS the codes against this file.
 *
 * ⚠ PASTE 2.6b, DO NOT RETYPE IT. The block is emitted already shaped like the
 * array below precisely so no human transcribes 175 rows. The last hand-built
 * territory fixture in this arc was written in alpha-2 where Apple speaks
 * alpha-3, looked correct throughout, and was caught only by a count (P27 #4).
 *
 * ⚠ THIS IS A PHOTOGRAPH. Apple changes which territories it sells to — it
 * has done so before and will again. Nothing in this repo makes that change
 * appear here; a human runs the probe and edits this array. Treat every row
 * below as "true on 2026-08-27", never as "true".
 *
 * ─── WHY A SNAPSHOT AND NOT A LIVE READ ────────────────────────────────────
 *
 * The export needs this list to answer "all countries" (`[Q-EXPORT.union-
 * columns]`): the columns are the UNION of the territory catalog and Apple's
 * list, so that a country is never silently dropped by either side. Reading
 * `/v1/territories` per export would add a request to the one route whose
 * whole constraint is Apple's hourly budget, and would make the file's shape
 * depend on a network call that can fail — turning a column layout into
 * something that varies with Apple's uptime.
 *
 * ⚠ AND A SNAPSHOT THAT NOBODY CHECKS IS A LIE WITH A DATE ON IT. Two
 * detectors exist, on purpose, because they fail in opposite directions:
 *
 *   (a) THE PROBE DIFF — complete, but only runs when a human remembers.
 *       Sees additions AND removals, because it compares whole lists.
 *
 *   (b) THE RUNTIME WARNING — automatic, but partial. `unknownAppleTerritories`
 *       is called on every export with the codes Apple actually returned, and
 *       logs the ones this file does not know. It cannot see a REMOVAL (a
 *       territory Apple dropped simply stops appearing, which is
 *       indistinguishable from an item not being sold there) — but an
 *       ADDITION is the case that costs the Manager a missing column, and it
 *       catches that with nobody remembering anything.
 *
 * Neither alone is enough: (a) is complete and forgettable, (b) is automatic
 * and half-blind. Cost of (b) is one Set lookup per price row and a log line
 * that is silent in the normal case.
 *
 * ⚠ THE WARNING NEVER BLOCKS AN EXPORT. An unknown territory still gets its
 * price and its column — `buildExportPlan` unions the codes it actually saw
 * on top of the expansion, so a market Apple added yesterday still exports
 * today. The log is how we learn to refresh the file, not a gate.
 */

/** One territory as Apple describes it. */
export interface AppleTerritory {
  /** ⚠ ALPHA-3 — Apple's own alphabet. The export speaks alpha-2 and converts
   *  at the boundary via `territory-code-map` (the only thing that knows
   *  Kosovo is `XKS` here and `XK` everywhere else). A fixture that mixed the
   *  two already cost this arc a debugging round: the codes looked plausible
   *  and only the COUNT was wrong. */
  code: string;
  /**
   * ⚠ THE CURRENCY APPLE BILLS THIS MARKET IN — NOT THE COUNTRY'S OWN.
   *
   * Measured, and the measurement is the point: **96 of the 164 territories
   * this catalog shares with `TERRITORY_CATALOG` disagree (58.5%)**, because
   * Apple collapses 93 markets to USD and 3 to EUR rather than billing
   * locally. Bulgaria is EUR, not BGN. Macau is USD, not MOP. Iceland is USD,
   * not ISK. Bermuda and Cayman are USD despite having BMD and KYD.
   *
   * ⇒ **Currency can never be derived from a country code.** Any code that
   * maps territory → currency without asking Apple is wrong for more than
   * half of Apple's markets. See KB §4.19.
   */
  currency: string;
}

/**
 * Apple's territories, with the currency Apple bills each one in.
 *
 * ⚠ Generated by pasting the probe's step-2.6b block, never retyped — see the
 * file header. Transcription was verified three ways before this file was
 * written: the code set matched the previous snapshot exactly (which step 2.7
 * had just confirmed IN SYNC with live Apple), every currency is well-formed,
 * and the eight values quoted independently in prose all agreed.
 */
export const APPLE_TERRITORIES: readonly AppleTerritory[] = [
  { code: "AFG", currency: "USD" }, { code: "AGO", currency: "USD" }, { code: "AIA", currency: "USD" }, { code: "ALB", currency: "USD" },
  { code: "ARE", currency: "AED" }, { code: "ARG", currency: "USD" }, { code: "ARM", currency: "USD" }, { code: "ATG", currency: "USD" },
  { code: "AUS", currency: "AUD" }, { code: "AUT", currency: "EUR" }, { code: "AZE", currency: "USD" }, { code: "BEL", currency: "EUR" },
  { code: "BEN", currency: "USD" }, { code: "BFA", currency: "USD" }, { code: "BGR", currency: "EUR" }, { code: "BHR", currency: "USD" },
  { code: "BHS", currency: "USD" }, { code: "BIH", currency: "EUR" }, { code: "BLR", currency: "USD" }, { code: "BLZ", currency: "USD" },
  { code: "BMU", currency: "USD" }, { code: "BOL", currency: "USD" }, { code: "BRA", currency: "BRL" }, { code: "BRB", currency: "USD" },
  { code: "BRN", currency: "USD" }, { code: "BTN", currency: "USD" }, { code: "BWA", currency: "USD" }, { code: "CAN", currency: "CAD" },
  { code: "CHE", currency: "CHF" }, { code: "CHL", currency: "CLP" }, { code: "CHN", currency: "CNY" }, { code: "CIV", currency: "USD" },
  { code: "CMR", currency: "USD" }, { code: "COD", currency: "USD" }, { code: "COG", currency: "USD" }, { code: "COL", currency: "COP" },
  { code: "CPV", currency: "USD" }, { code: "CRI", currency: "USD" }, { code: "CYM", currency: "USD" }, { code: "CYP", currency: "EUR" },
  { code: "CZE", currency: "CZK" }, { code: "DEU", currency: "EUR" }, { code: "DMA", currency: "USD" }, { code: "DNK", currency: "DKK" },
  { code: "DOM", currency: "USD" }, { code: "DZA", currency: "USD" }, { code: "ECU", currency: "USD" }, { code: "EGY", currency: "EGP" },
  { code: "ESP", currency: "EUR" }, { code: "EST", currency: "EUR" }, { code: "FIN", currency: "EUR" }, { code: "FJI", currency: "USD" },
  { code: "FRA", currency: "EUR" }, { code: "FSM", currency: "USD" }, { code: "GAB", currency: "USD" }, { code: "GBR", currency: "GBP" },
  { code: "GEO", currency: "USD" }, { code: "GHA", currency: "USD" }, { code: "GMB", currency: "USD" }, { code: "GNB", currency: "USD" },
  { code: "GRC", currency: "EUR" }, { code: "GRD", currency: "USD" }, { code: "GTM", currency: "USD" }, { code: "GUY", currency: "USD" },
  { code: "HKG", currency: "HKD" }, { code: "HND", currency: "USD" }, { code: "HRV", currency: "EUR" }, { code: "HUN", currency: "HUF" },
  { code: "IDN", currency: "IDR" }, { code: "IND", currency: "INR" }, { code: "IRL", currency: "EUR" }, { code: "IRQ", currency: "USD" },
  { code: "ISL", currency: "USD" }, { code: "ISR", currency: "ILS" }, { code: "ITA", currency: "EUR" }, { code: "JAM", currency: "USD" },
  { code: "JOR", currency: "USD" }, { code: "JPN", currency: "JPY" }, { code: "KAZ", currency: "KZT" }, { code: "KEN", currency: "USD" },
  { code: "KGZ", currency: "USD" }, { code: "KHM", currency: "USD" }, { code: "KNA", currency: "USD" }, { code: "KOR", currency: "KRW" },
  { code: "KWT", currency: "USD" }, { code: "LAO", currency: "USD" }, { code: "LBN", currency: "USD" }, { code: "LBR", currency: "USD" },
  { code: "LBY", currency: "USD" }, { code: "LCA", currency: "USD" }, { code: "LKA", currency: "USD" }, { code: "LTU", currency: "EUR" },
  { code: "LUX", currency: "EUR" }, { code: "LVA", currency: "EUR" }, { code: "MAC", currency: "USD" }, { code: "MAR", currency: "USD" },
  { code: "MDA", currency: "USD" }, { code: "MDG", currency: "USD" }, { code: "MDV", currency: "USD" }, { code: "MEX", currency: "MXN" },
  { code: "MKD", currency: "USD" }, { code: "MLI", currency: "USD" }, { code: "MLT", currency: "EUR" }, { code: "MMR", currency: "USD" },
  { code: "MNE", currency: "EUR" }, { code: "MNG", currency: "USD" }, { code: "MOZ", currency: "USD" }, { code: "MRT", currency: "USD" },
  { code: "MSR", currency: "USD" }, { code: "MUS", currency: "USD" }, { code: "MWI", currency: "USD" }, { code: "MYS", currency: "MYR" },
  { code: "NAM", currency: "USD" }, { code: "NER", currency: "USD" }, { code: "NGA", currency: "NGN" }, { code: "NIC", currency: "USD" },
  { code: "NLD", currency: "EUR" }, { code: "NOR", currency: "NOK" }, { code: "NPL", currency: "USD" }, { code: "NRU", currency: "USD" },
  { code: "NZL", currency: "NZD" }, { code: "OMN", currency: "USD" }, { code: "PAK", currency: "PKR" }, { code: "PAN", currency: "USD" },
  { code: "PER", currency: "PEN" }, { code: "PHL", currency: "PHP" }, { code: "PLW", currency: "USD" }, { code: "PNG", currency: "USD" },
  { code: "POL", currency: "PLN" }, { code: "PRT", currency: "EUR" }, { code: "PRY", currency: "USD" }, { code: "QAT", currency: "QAR" },
  { code: "ROU", currency: "RON" }, { code: "RUS", currency: "RUB" }, { code: "RWA", currency: "USD" }, { code: "SAU", currency: "SAR" },
  { code: "SEN", currency: "USD" }, { code: "SGP", currency: "SGD" }, { code: "SLB", currency: "USD" }, { code: "SLE", currency: "USD" },
  { code: "SLV", currency: "USD" }, { code: "SRB", currency: "EUR" }, { code: "STP", currency: "USD" }, { code: "SUR", currency: "USD" },
  { code: "SVK", currency: "EUR" }, { code: "SVN", currency: "EUR" }, { code: "SWE", currency: "SEK" }, { code: "SWZ", currency: "USD" },
  { code: "SYC", currency: "USD" }, { code: "TCA", currency: "USD" }, { code: "TCD", currency: "USD" }, { code: "THA", currency: "THB" },
  { code: "TJK", currency: "USD" }, { code: "TKM", currency: "USD" }, { code: "TON", currency: "USD" }, { code: "TTO", currency: "USD" },
  { code: "TUN", currency: "USD" }, { code: "TUR", currency: "TRY" }, { code: "TWN", currency: "TWD" }, { code: "TZA", currency: "TZS" },
  { code: "UGA", currency: "USD" }, { code: "UKR", currency: "USD" }, { code: "URY", currency: "USD" }, { code: "USA", currency: "USD" },
  { code: "UZB", currency: "USD" }, { code: "VCT", currency: "USD" }, { code: "VEN", currency: "USD" }, { code: "VGB", currency: "USD" },
  { code: "VNM", currency: "VND" }, { code: "VUT", currency: "USD" }, { code: "XKS", currency: "EUR" }, { code: "YEM", currency: "USD" },
  { code: "ZAF", currency: "ZAR" }, { code: "ZMB", currency: "USD" }, { code: "ZWE", currency: "USD" },
];

/** Codes only. ⚠ DERIVED, never a second hand-maintained list — two lists that
 *  must agree are two lists that will not. */
export const APPLE_TERRITORIES_ALPHA3: readonly string[] =
  APPLE_TERRITORIES.map((t) => t.code);

/** Alpha-3 → the currency Apple bills in. `null` for anything not in the
 *  snapshot, so a caller cannot silently receive a guess. */
export function appleCurrencyFor(alpha3: string): string | null {
  return CURRENCY_BY_CODE.get(alpha3) ?? null;
}

const CURRENCY_BY_CODE: ReadonlyMap<string, string> = new Map(
  APPLE_TERRITORIES.map((t) => [t.code, t.currency]),
);

/** Fast membership for the runtime detector. Built once at module load. */
const APPLE_SET: ReadonlySet<string> = new Set(APPLE_TERRITORIES_ALPHA3);

/**
 * Detector (b) — Apple alpha-3 codes this snapshot does not know about.
 *
 * ⚠ PURE, and deduped, so the caller decides whether to log and the test can
 * assert without capturing console. Returns `[]` in the normal case, which is
 * the case that must stay free.
 *
 * ⚠ ADDITIONS ONLY, by construction. It is handed the codes Apple returned,
 * so a territory Apple REMOVED cannot appear in the input and cannot be
 * detected here — that is detector (a)'s job. Stated rather than left for
 * someone to discover the day a removal slips through.
 */
export function unknownAppleTerritories(
  observed: readonly string[],
): string[] {
  const out = new Set<string>();
  for (const code of observed) {
    if (!APPLE_SET.has(code)) out.add(code);
  }
  return [...out].sort();
}
